title = "Artificial Intelligence Translational Research Lab"
baseURL = "https://aitr-lab.github.io/"
theme = "researcher"
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
disableKinds = ["taxonomy", "term"]

[params]
titleAbbr = "AITR"
author = "AITR"
description = "AITR is a research lab working on deveoping applying foundational AI and machine learning methods to solve real-world problems across domains such as document analysis, computer vision, and medical imaging. "
favicon = "favicon.ico"  # path to a .ico to use as favicon
css = ["css/custom.css"]
googleAnalytics = "UA-186917619-1"
footer = { text = "Welcome to AITR" }


[permalinks]
"/" = "/:filename"

[menu]

[[menu.main]]
  name = "People"
  url = "/people"
  weight = 1

[[menu.main]]
  name = "News"
  url = "/news"
  weight = 3

[[menu.main]]
  name = "Publications"
  url = "/Publication"
  weight = 4

[markup.goldmark.renderer]
unsafe = true  # allow raw HTML in markdown files
